### ISSUE TITLE
Z80 has GameBoy CPU

### ISSUE THREAD

**Issue by toxinu** [lliendo/PyZ80#5]
Hi @lliendo ,

Thank you for your work!
I am writing a GameBoy emulator for learning purposes and I want to know if your module can fit in my project. I am a beginner in machine/CPU emulation.

Will you write some documentations in a near future ?

**Comment by lliendo** [comment]
Hi Geoffrey ! Thanks for your interest. Currently I'm implementing the last
group of instructions (exchange & transfer, cpu control and i/o). I use as
a primary guides 'The undocumented Z80 Documented' by Sean Young and also
the official Z80 user manual. I'm not planning on the near future
documentation for my project because the code is simple enough to read and
understand how it works, but if you have any questions that I can help you
out just send me an email. Also take into consideration that emulating a
whole system goes much beyond just emulating a CPU, you will have to fully
understand how a GameBoy system is composed an emulate all related
components or devices (input, sound, video & cpu, etc). I would suggest
that you look into a more mature z80 implementation as this project is a
hobby for me and might not finish it soon. I'm also a beginner in this
stuff !

On Mon, Jan 12, 2015 at 8:22 AM, Geoffrey Lehée <notifications@github.com>
wrote:

> Hi @lliendo <https://github.com/lliendo> ,
>
> Thank you for your work!
> I am writing a GameBoy emulator for learning purposes and I want to know
> if your module can fit in my project. I am a beginner in machine/CPU
> emulation.
>
> Will you write some documentations in a near future ?
>
> Best regards,
> Socketubs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lliendo/PyZ80/issues/5>.
>



-- 

Cheers,
Lucas.
   _
__("<
\__/
 ^^

**Comment by socketubs** [comment]
@lliendo Sorry for being late!
Thank you for your advices. Im still not on this project for now (not enought time you know), but I keep your PyZ80 project in my bookmarks :smile:
